apiVersion: v1
kind: Service
metadata:
  name: vueocredge-service
  labels:
    app: vueocredge-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32098
  selector:
    app: vueocredge
